name: "Test"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: cachix/install-nix-action@v13
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v9
      with:
        name: mycache
        # If you chose API tokens for write access OR if you have a private cache
        authToken: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJjJDI3MjEiLCJqdGkiOiJlZDI1YjM5My00NzQ0LTQ5MWUtYjA5YS00NTBhOTJlNTdhMmUiLCJzY29wZXMiOiJjYWNoZSJ9.FA-9_O2yLqt2r7jQ9zRdAIHdXn2uuskQraAXinA9UCY
    - run: nix-build
    - run: nix-shell --run "echo OK"
